const Terms = () => (
  <main className="min-h-screen bg-background text-surface-dark-fg">
    <section className="py-24 lg:py-32">
      <div className="container mx-auto px-6">
        <div className="mx-auto max-w-4xl space-y-10">
          <div className="rounded-[2rem] border border-surface-dark-fg/10 bg-surface-dark p-10 shadow-[0_25px_100px_rgba(0,0,0,0.08)] backdrop-blur-xl">
            <div className="space-y-6">
              <div className="space-y-3">
                <p className="text-sm uppercase tracking-[0.4em] text-primary font-semibold font-body">MOGG APP</p>
                <h1 className="text-4xl md:text-5xl font-black leading-tight tracking-tight font-display">Terms of Service</h1>
                <p className="text-sm text-surface-dark-fg/60 font-body">Effective Date: April 8, 2026</p>
              </div>

              <div className="space-y-8 text-sm leading-7 text-surface-dark-fg/85 font-body">
                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">1. Acceptance of Terms</h2>
                  <p>By downloading, accessing, or using MOGG APP ("the App"), you agree to be bound by these Terms of Service ("Terms"). If you do not agree to these Terms, do not use the App. These Terms apply to all users, including visitors and registered account holders.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">2. Description of Service</h2>
                  <p>MOGG APP is an AI-powered looksmaxxing application that allows users to upload photos of their face to receive aesthetic ratings, feature analysis, and appearance improvement suggestions. The App is intended for entertainment and self-improvement purposes only.</p>
                  <p className="font-semibold">IMPORTANT: Ratings and suggestions provided by MOGG APP are generated by artificial intelligence and are NOT medical advice, psychological assessments, or professional opinions of any kind.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">3. Eligibility</h2>
                  <p>You must be at least 13 years of age to use this App. If you are under 18, you must have parental or guardian consent. By using the App, you confirm that you meet these age requirements. We reserve the right to terminate accounts of users who misrepresent their age.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">4. Account Registration</h2>
                  <p>To access certain features, you may need to create an account. You agree to:</p>
                  <ul className="list-inside list-disc space-y-2 pl-5">
                    <li>Provide accurate and complete registration information</li>
                    <li>Keep your account credentials confidential</li>
                    <li>Notify us immediately of any unauthorized access to your account</li>
                    <li>Accept responsibility for all activity that occurs under your account</li>
                  </ul>
                  <p>We reserve the right to terminate accounts at our discretion.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">5. Facial Photo Data & Biometric Information</h2>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">5.1 How We Handle Your Photos</h3>
                      <ul className="list-inside list-disc space-y-2 pl-5">
                        <li>Your photo is processed by our AI model solely to generate your rating and analysis</li>
                        <li>Photos are not permanently stored on our servers beyond the time required to process your request</li>
                        <li>We do not sell, share, or transfer your facial photos to any third party</li>
                        <li>We do not use your photos to train AI models without explicit consent</li>
                      </ul>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">5.2 Your Consent</h3>
                      <p>By uploading a photo, you grant MOGG APP a limited, temporary license to process that image for the purpose of generating your results. This license expires upon completion of the analysis.</p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">5.3 Biometric Data</h3>
                      <p>If applicable law in your jurisdiction classifies facial geometry derived from photos as biometric data (e.g., Illinois BIPA, GDPR), we handle such data in compliance with those regulations. You may request deletion of your data at any time by contacting us at mooggapp@gmail.com.</p>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">6. User-Generated Content</h2>
                  <p>By uploading content to MOGG APP, you represent that:</p>
                  <ul className="list-inside list-disc space-y-2 pl-5">
                    <li>You own or have the right to use the content you upload</li>
                    <li>The content does not depict any person under the age of 18</li>
                    <li>The content does not violate any third-party rights</li>
                    <li>You will not upload content that is hateful, obscene, or illegal</li>
                  </ul>
                  <p>We reserve the right to remove any content that violates these Terms without notice.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">7. Purchases & Subscriptions</h2>
                  <div className="space-y-4">
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">7.1 One-Time Purchases</h3>
                      <p>Certain features or items may be available for one-time purchase. All purchases are final and non-refundable unless required by applicable law.</p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">7.2 Subscription Plans</h3>
                      <p>MOGG APP offers subscription plans that grant access to premium features. Subscriptions automatically renew unless cancelled before the renewal date. You may cancel your subscription at any time through your account settings or the applicable app store.</p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">7.3 Free Trial</h3>
                      <p>We may offer a free trial period for subscription plans. At the end of the free trial, your subscription will automatically convert to a paid plan unless you cancel before the trial ends.</p>
                    </div>
                    <div>
                      <h3 className="text-lg font-semibold text-surface-dark-fg">7.4 Price Changes</h3>
                      <p>We reserve the right to change subscription pricing. We will provide reasonable notice of any price changes before they take effect.</p>
                    </div>
                  </div>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">8. Intellectual Property</h2>
                  <p>All content, logos, trademarks, visual design, software, and technology within MOGG APP are the exclusive property of MOGG APP and its licensors. You may not copy, reproduce, distribute, or create derivative works from any part of the App without prior written permission.</p>
                  <p>The MOGG name, logo, and brand identity are registered trademarks. Unauthorized use is strictly prohibited.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">9. Feedback & Suggestions</h2>
                  <p>If you provide us with feedback, ideas, or suggestions about the App, you agree that we may implement such feedback without compensation or credit to you. By submitting feedback, you waive any claim of ownership or compensation related to that feedback.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">10. Promotions & Contests</h2>
                  <p>MOGG APP may offer promotions, contests, or sweepstakes from time to time. Each promotion will be governed by its own specific rules, which will be made available at the time of the promotion. Participation constitutes acceptance of those rules.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">11. Prohibited Conduct</h2>
                  <ul className="list-inside list-disc space-y-2 pl-5">
                    <li>Use the App for any unlawful purpose</li>
                    <li>Upload photos of other people without their consent</li>
                    <li>Attempt to reverse-engineer, hack, or exploit the App</li>
                    <li>Use automated bots or scrapers on the App</li>
                    <li>Harass, bully, or harm other users</li>
                    <li>Circumvent any security or access controls</li>
                    <li>Use the App in a way that could damage our reputation or business</li>
                  </ul>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">12. Disclaimer of Warranties</h2>
                  <p>MOGG APP is provided "as is" and "as available" without any warranties of any kind, express or implied. We do not warrant that the App will be uninterrupted, error-free, or free of viruses. We make no guarantees regarding the accuracy of AI-generated ratings or suggestions.</p>
                  <p>Results from MOGG APP are for entertainment purposes only and should not be taken as medical, psychological, or professional advice. We are not responsible for any emotional distress arising from the use of the App.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">13. Limitation of Liability</h2>
                  <p>To the maximum extent permitted by law, MOGG APP and its owners, employees, and affiliates shall not be liable for any indirect, incidental, special, or consequential damages arising from your use of the App, including but not limited to emotional distress, loss of data, or financial loss.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">14. Copyright Infringement (DMCA)</h2>
                  <p>If you believe that content on MOGG APP infringes your copyright, please send a DMCA notice to our designated Copyright Agent at:</p>
                  <p>Email: mooggapp@gmail.com</p>
                  <p>Please include a description of the copyrighted work, the location of the infringing content, your contact information, and a statement of good faith belief that the use is not authorized.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">15. Termination</h2>
                  <p>We reserve the right to suspend or terminate your account and access to the App at any time, for any reason, including violation of these Terms. Upon termination, your right to use the App ceases immediately.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">16. Changes to These Terms</h2>
                  <p>We may update these Terms at any time. When we do, we will update the effective date at the top of this page. Continued use of the App after changes constitutes your acceptance of the new Terms. We recommend reviewing these Terms periodically.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">17. Governing Law</h2>
                  <p>These Terms are governed by and construed in accordance with applicable law. Any disputes arising from these Terms or your use of the App shall be resolved through binding arbitration or in the courts of competent jurisdiction.</p>
                </section>

                <section className="space-y-4">
                  <h2 className="text-xl font-semibold text-surface-dark-fg">18. Contact Us</h2>
                  <p>If you have any questions about these Terms of Service, please contact us:</p>
                  <p className="font-semibold">MOGG APP</p>
                  <p>Email: mooggapp@gmail.com</p>
                  <p>Instagram: @mogg_app</p>
                  <p className="mt-4 font-semibold">MOGG AND GET MOGGED — The #1 Looksmaxxing App</p>
                </section>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
  </main>
);

export default Terms;
